### ISSUE TITLE
Compile issues when compiling nginx 1.6.2 with nginx-clojure master

### ISSUE THREAD

**Issue by tyderia** [nginx-clojure/nginx-clojure#71]
Compiling on and for Centos 7:

[...]
        -o objs/addon/c/ngx_http_clojure_module.o \
        /tmp/rpmbuild/BUILD/nginx-1.6.2/nginx-clojure-master/src/c/ngx_http_clojure_module.c
cc -c -I "/usr/java/latest/include"         -I "/usr/java/latest/include/linux"         -DNGX_CLOJURE_BE_SILENT_WITHOUT_JVM           -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/include/luajit-2.0/ -I /tmp/rpmbuild/BUILD/nginx-1.6.2/lua-nginx-module-0.9.15/src/api -I /tmp/rpmbuild/BUILD/nginx-1.6.2/ngx_devel_kit-0.2.19/objs -I objs/addon/ndk -I objs -I src/http -I src/http/modules -I /tmp/rpmbuild/BUILD/nginx-1.6.2/ngx_devel_kit-0.2.19/src -I src/mail \
        -o objs/addon/c/ngx_http_clojure_socket.o \
        /tmp/rpmbuild/BUILD/nginx-1.6.2/nginx-clojure-master/src/c/ngx_http_clojure_socket.c
/tmp/rpmbuild/BUILD/nginx-1.6.2/nginx-clojure-master/src/c/ngx_http_clojure_socket.c: In function 'jni_ngx_http_clojure_socket_bind_str':
/tmp/rpmbuild/BUILD/nginx-1.6.2/nginx-clojure-master/src/c/ngx_http_clojure_socket.c:562:3: error: pointer targets in passing argument 1 of 'atoi' differ in signedness [-Werror=pointer-sign]
   port = atoi(pport + 1);
   ^
In file included from /usr/include/features.h:375:0,
                 from /usr/include/sys/types.h:25,
                 from src/os/unix/ngx_linux_config.h:18,
                 from src/core/ngx_config.h:26,
                 from /tmp/rpmbuild/BUILD/nginx-1.6.2/nginx-clojure-master/src/c/ngx_http_clojure_socket.c:5:
/usr/include/stdlib.h:278:1: note: expected 'const char *' but argument is of type 'u_char *'
 __NTH (atoi (const char *__nptr))
 ^
/tmp/rpmbuild/BUILD/nginx-1.6.2/nginx-clojure-master/src/c/ngx_http_clojure_socket.c:565:96: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
  if (ngx_parse_addr(u->pool,  paddr,  paddr->name.data,  port != -1 ? pport - paddr->name.data :  paddr->name.len) != NGX_OK) {
                                                                                                ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/c/ngx_http_clojure_socket.o] Error 1
make[1]: Leaving directory `/tmp/rpmbuild/BUILD/nginx-1.6.2'
make: *** [build] Error 2

**Comment by xfeep** [comment]
Please try again.

**Comment by tyderia** [comment]
Yes, it builds now. I see that the version of the nginx-clojure jar file that is required has incremented to 0.4.0 at some point, but that's not available in binary distribution yet. I'll have to figure out how to build it too before I can confirm that nginx-clojure works for me. My build acceptance test fails now with nginx reporting "too low version jar of nginx-clojure, we need at least 0.4.0, but meet 0.3.0". I'm using the 0.3.0 jar file at the moment of course.

Hopefully the 0.4.0 release is coming soon?

**Comment by tyderia** [comment]
Thank you, btw!

**Comment by xfeep** [comment]
The master branch is on the road to release v0.4.0.
If you only need v0.3.0 please compile with tag v0.3.0 or commit 961569ab4513b63f4d220677a17d0d417d943b12, the later resolves some compile errors on ubuntu.
If you want to try the lastest   please use `lein jar` to compile the source and get the latest jar file.
