### ISSUE TITLE
make nginx-clojure-0.4.4 error

### ISSUE THREAD

**Issue by slieer** [nginx-clojure/nginx-clojure#133]
CentOS Linux release 7.2.1511 (Core)
- Linux 3.10.0-327.28.2.el7.x86_64 x86_64
- using GNU C compiler
- gcc version: 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

make error:
/opt/nginx/nginx-clojure-code/nginx-clojure-0.4.4//src/c/ngx_http_clojure_socket.c: In function ‘ngx_http_clojure_socket_upstream_connect_by_url’:
/opt/nginx/nginx-clojure-code/nginx-clojure-0.4.4//src/c/ngx_http_clojure_socket.c:320:54: error: cannot convert to a pointer type
  ngx_http_clojure_socket_upstream_connect(u, (struct sockaddr *)url->sockaddr, url->socklen);

**Comment by xfeep** [comment]
I think it's same with #121. Commit ff68322 fixed it.

**Comment by oubiwann** [comment]
I came across this error too and can confirm that `master` fixes the issue (I get a successful build with that, but not with 0.4.4).

@xfeep Thanks!

**Comment by xfeep** [comment]
@oubiwann Thank you for letting me know.
