### ISSUE TITLE
nginx-1.11.6 - pointer conversion error

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#149]
when trying to compile with nginx-1.11.6 this is error i'm receiving:

`	/etc/nginx-clojure/nginx-clojure-0.4.4/src/c/ngx_http_clojure_socket.c
/etc/nginx-clojure/nginx-clojure-0.4.4/src/c/ngx_http_clojure_socket.c: In function 'ngx_http_clojure_socket_upstream_connect_by_url':
/etc/nginx-clojure/nginx-clojure-0.4.4/src/c/ngx_http_clojure_socket.c:320:54: error: cannot convert to a pointer type
  ngx_http_clojure_socket_upstream_connect(u, (struct sockaddr *)url->sockaddr, url->socklen);`

**Comment by xfeep** [comment]
Commit ff68322 fixed it.Please try the master branch.

**Comment by knasim** [comment]
@xfeep - yes it did thanks !

**Comment by knasim** [comment]
Although when I `make install`  it errors out saying /conf/koi-win is the same file.  
it is trying to copy the same file to the same location?

**Comment by xfeep** [comment]
Did you install Nginx before running `make install`?

**Comment by knasim** [comment]
hello @xfeep  - you must have been on long holiday !

this is not an issue.   iif you do `make install` from same location where you built nginx then you will get this error - it makes sense because build location and install location cannot be the same.  
you have to specify different `prefix` when you build and install nginx.
