### ISSUE TITLE
No access to tomcat server from nginx-clojure

### ISSUE THREAD

**Issue by Asprelis** [nginx-clojure/nginx-clojure#82]
I see a strange behavior  - if i startup my tomcat server separately (on different port) i can access to its web apps (i using tomcat greetings page, which is just localhost:port/ (ROOT)). 
When i run my nginx-clojure - i can see in logs the same that i see when running startup.bat of tomcat. Everything is fine... initialization processed... But tomcat not listen to any port, nginx listening to 8080 by default. When i try to access tomcat greetings page (or any other application page) i'm getting error:

    2015-07-07 09:12:29[error]:server unhandled exception!
    java.lang.NoSuchMethodError: org.apache.tomcat.util.net.SocketWrapper.reset(Ljava/lang/Object;J)V
	at org.apache.coyote.http11.NginxEndpoint$KeyAttachment.reset(NginxEndpoint.java:227)
	at org.apache.coyote.http11.NginxEndpoint.register(NginxEndpoint.java:411)
	at org.apache.coyote.http11.NginxEndpoint.accept(NginxEndpoint.java:475)
	at nginx.clojure.tomcat8.NginxTomcatBridge.handle(NginxTomcatBridge.java:244)
	at nginx.clojure.bridge.NginxBridgeHandler.invoke(NginxBridgeHandler.java:40)
	at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:93)
	at nginx.clojure.NginxSimpleHandler.handleRequest(NginxSimpleHandler.java:150)
	at nginx.clojure.NginxSimpleHandler.execute(NginxSimpleHandler.java:92)
	at nginx.clojure.NginxClojureRT.eval(NginxClojureRT.java:1063)

Here is log from nginx when i starting it (it says that all is fine):

	2015-07-07 09:12:19[info]:set system property: catalina.home=D:/nginx-closure/apache-tomcat-8.0.23
	2015-07-07 09:12:19[info]:set system property: catalina.base=D:/nginx-closure/apache-tomcat-8.0.23
	2015-07-07 09:12:19[info]:set system property: java.util.logging.manager=org.apache.juli.ClassLoaderLogManager
	2015-07-07 09:12:19[info]:nginx.clojure.tomcat8.NginxTomcatBridge.boot() with whole classpath: [file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/annotations-api.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/catalina-ant.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/catalina-ha.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/catalina-storeconfig.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/catalina-tribes.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/catalina.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/ecj-4.4.2.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/el-api.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/jasper-el.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/jasper.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/jsp-api.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/servlet-api.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-api.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-coyote.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-dbcp.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-i18n-es.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-i18n-fr.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-i18n-ja.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-jdbc.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-jni.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-util-scan.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-util.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/tomcat-websocket.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/lib/websocket-api.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/bin/bootstrap.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/bin/commons-daemon.jar, file:/D:/nginx-closure/apache-tomcat-8.0.23/bin/tomcat-juli.jar, file:/D:/nginx-closure/nginx-clojure-0.4.0/nginx-1.8.0/jars/nginx-tomcat8-0.1.0.jar]
	июл 07, 2015 9:12:19 AM nginx.clojure.tomcat8.NginxTomcatBridge boot
	INFO: tomcatHome=D:\nginx-closure\apache-tomcat-8.0.23, conf=conf/server.xml
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: Server version:        Apache Tomcat/8.0.23
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: Server built:          May 19 2015 14:58:38 UTC
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: Server number:         8.0.23.0
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: OS Name:               Windows 7
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: OS Version:            6.1
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: Architecture:          amd64
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: Java Home:             C:\Program Files\Java\jdk1.8.0_05\jre
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: JVM Version:           1.8.0_05-b13
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: JVM Vendor:            Oracle Corporation
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: CATALINA_BASE:         D:\nginx-closure\apache-tomcat-8.0.23
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.VersionLoggerListener log
	INFO: CATALINA_HOME:         D:\nginx-closure\apache-tomcat-8.0.23
	июл 07, 2015 9:12:19 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
	INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: D:\nginx-closure\nginx-clojure-0.4.0\nginx-1.8.0;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\NetBeans 8.0.1\java\maven\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\OpenVPN\bin;C:\Program Files (x86)\scala\bin;.
	июл 07, 2015 9:12:19 AM org.apache.coyote.AbstractProtocol init
	INFO: Initializing ProtocolHandler ["http-nginx-auto-1-0"]
	июл 07, 2015 9:12:19 AM org.apache.coyote.http11.NginxEndpoint bind
	INFO: skip bind because nginx has already done it.
	июл 07, 2015 9:12:19 AM org.apache.catalina.core.StandardService startInternal
	INFO: Starting service Catalina
	июл 07, 2015 9:12:19 AM org.apache.catalina.core.StandardEngine startInternal
	INFO: Starting Servlet Engine: Apache Tomcat/8.0.23
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.HostConfig deployWAR
	INFO: Deploying web application archive D:\nginx-closure\apache-tomcat-8.0.23\webapps\SecurConfig.war
	июл 07, 2015 9:12:19 AM org.apache.catalina.startup.SetContextPropertiesRule begin
	WARNING: [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property.
	июл 07, 2015 9:12:21 AM org.apache.jasper.servlet.TldScanner scanJars
	INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
	июл 07, 2015 9:12:21 AM org.apache.catalina.core.ApplicationContext log
	INFO: No Spring WebApplicationInitializer types detected on classpath
	июл 07, 2015 9:12:21 AM org.apache.catalina.core.ApplicationContext log
	INFO: Initializing Spring root WebApplicationContext
	июл 07, 2015 9:12:23 AM org.apache.catalina.core.ApplicationContext log
	INFO: Initializing Spring FrameworkServlet 'dispatcherServlet'
	июл 07, 2015 9:12:23 AM org.apache.catalina.startup.HostConfig deployWAR
	INFO: Deployment of web application archive D:\nginx-closure\apache-tomcat-8.0.23\webapps\SecurConfig.war has finished in 4,364 ms
	июл 07, 2015 9:12:23 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deploying web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\docs
	июл 07, 2015 9:12:24 AM org.apache.jasper.servlet.TldScanner scanJars
	INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deployment of web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\docs has finished in 163 ms
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deploying web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\examples
	июл 07, 2015 9:12:24 AM org.apache.jasper.servlet.TldScanner scanJars
	INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
	июл 07, 2015 9:12:24 AM org.apache.catalina.core.ApplicationContext log
	INFO: ContextListener: contextInitialized()
	июл 07, 2015 9:12:24 AM org.apache.catalina.core.ApplicationContext log
	INFO: SessionListener: contextInitialized()
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deployment of web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\examples has finished in 265 ms
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deploying web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\host-manager
	июл 07, 2015 9:12:24 AM org.apache.jasper.servlet.TldScanner scanJars
	INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deployment of web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\host-manager has finished in 158 ms
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deploying web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\manager
	июл 07, 2015 9:12:24 AM org.apache.jasper.servlet.TldScanner scanJars
	INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deployment of web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\manager has finished in 301 ms
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deploying web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\ROOT
	июл 07, 2015 9:12:24 AM org.apache.jasper.servlet.TldScanner scanJars
	INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.HostConfig deployDirectory
	INFO: Deployment of web application directory D:\nginx-closure\apache-tomcat-8.0.23\webapps\ROOT has finished in 151 ms
	июл 07, 2015 9:12:24 AM org.apache.coyote.AbstractProtocol start
	INFO: Starting ProtocolHandler ["http-nginx-auto-1-0"]
	июл 07, 2015 9:12:24 AM org.apache.catalina.startup.Catalina start
	INFO: Server startup in 5440 ms
	июл 07, 2015 9:12:24 AM nginx.clojure.tomcat8.NginxTomcatBridge boot
	INFO: Initialization processed in 5761 ms

And my conf file:

	###you can uncomment next two lines for easy debug
	###Warning: if master_process is off, there will be only one nginx worker running. Only use it for debug propose.

	#daemon  off;

	master_process  off;

	worker_processes  1;

	events {
		worker_connections  1024;
	}

	http {
		include       mime.types;
		default_type  application/octet-stream;

		sendfile        on;

		keepalive_timeout  65;

		#gzip  on;
		
		jvm_path "C:/Program Files/Java/jdk1.8.0_05/jre/bin/server/jvm.dll";
		
		jvm_var my_other_jars 'D:/nginx-closure/clojure-1.5.1.jar';
		
		###jvm_options can be repeated once per option. # note that : - unix, ; - windows separators
		jvm_options "-Djava.class.path=jars/nginx-clojure-0.4.0.jar;#{my_other_jars}";

		server {
			listen       8080;
			server_name  localhost;

			#charset koi8-r;

			#access_log  logs/host.access.log  main;
			
			# redirect server error pages to the static page /50x.html
			#
			error_page   500 502 503 504  /50x.html;
			location = /50x.html {
				root   html;
			}

		  location / {
                          content_handler_type java;
			  content_handler_name 'nginx.clojure.bridge.NginxBridgeHandler';

			  ##Tomcat 8 installation path
			  content_handler_property system.catalina.home 'D:/nginx-closure/apache-tomcat-8.0.23';
			  content_handler_property system.catalina.base '#{catalina.home}';

			  ##uncomment this to disable websocket perframe-compression
			  #content_handler_property system.org.apache.tomcat.websocket.DISABLE_BUILTIN_EXTENSIONS true;

			  ##log manger
			  content_handler_property system.java.util.logging.manager 'org.apache.juli.ClassLoaderLogManager';

			  ## all jars or direct child directories will be appended into the classpath of this bridge handler's class-loader
			  content_handler_property bridge.lib.dirs '#{catalina.home}/lib;#{catalina.home}/bin'; #dont forget to change ; to : on unix

			  ##set nginx tomcat8 bridge implementation jar and other jars can also be appended here
			  content_handler_property bridge.lib.cp 'D:/nginx-closure/nginx-clojure-0.4.0/nginx-1.8.0/jars/nginx-tomcat8-0.1.0.jar';

			  ##The implementation class of nginx-clojure bridge handler for Tomcat 8
			  content_handler_property bridge.imp 'nginx.clojure.tomcat8.NginxTomcatBridge';

			  ##ignore nginx filter, default is false
			  #content_handler_property ignoreNginxFilter false;

			  ##when dispatch is false tomcat servlet will be executed in main thread.By default dispatch is false
			  ##when use websocket with tomcat it must be set true otherwise maybe deadlock will happen.
			  #content_handler_property dispatch false;

			  gzip on;
			  gzip_types text/plain text/css 'text/html;charset=ISO-8859-1' 'text/html;charset=UTF-8'; 

			  ##if for small message, e.g. small json/websocket message write_page_size can set to be a small value
			  #write_page_size 2k;
		  }		
			
		   
		}

	}

**Comment by xfeep** [comment]
>Everything is fine... initialization processed... But tomcat not listen to any port, nginx listening to 8080 by default. 

Yes. tomcat won't listen to any port. Nginx do all low level network things. With nginx-clojure tomcat will  become only a servlet container.

>2015-07-07 09:12:29[error]:server unhandled exception!
java.lang.NoSuchMethodError: org.apache.tomcat.util.net.SocketWrapper.reset(Ljava/lang/Object;J)V

We only test it with tomcat 8.0.20. And tomcat-8.0.23 changed `org.apache.tomcat.util.net.SocketWrapper` and remove `reset` method.  This [link](http://svn.apache.org/viewvc/tomcat/tc8.0.x/trunk/java/org/apache/tomcat/util/net/SocketWrapper.java?r1=1659907&r2=1666109) show their difference. So it won't work with tomcat 8.0.23.

**Comment by Asprelis** [comment]
You were right! Thank you again.

**Comment by xfeep** [comment]
BTW, for performance reason please [follow this guide](https://github.com/nginx-clojure/nginx-clojure/tree/master/nginx-tomcat8#disable-logging-to-console) to disable tomcat logging to console (viz. tomcat logging to nginx error.log) because we can find all logging information from tomcat log files such as catalina-xxxx.log, manager-xxxx.log, localhost-xxxx.log.

**Comment by xfeep** [comment]
Hi, if you want to use it with tomcat 8.0.23, 8.0.24 please follow [this guide](http://nginx-clojure.github.io/more.html#310-embeding-tomcat) to compile nginx-tomcat8 v0.2.0 jar file by yourself. Thanks! 
BTW I reopen this issue now and won't close it until we release nginx-tomcat8 v0.2.0.
